name: Deploy Monitoring to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-monitoring:
    name: Deploy Prometheus & Grafana
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region eu-south-2 --name andrew-cluster1

      - name: Create Monitoring Namespace
        run: |
          kubectl create namespace monitoring || echo "Namespace already exists"

      - name: Deploy Prometheus & Grafana
        run: |
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --set grafana.adminPassword=admin123  # Change password if needed

      - name: Verify Deployment
        run: |
          kubectl get pods -n monitoring
          kubectl get svc -n monitoring
